var svg = d3.select("#mySVG")
   .append("svg")
   .attr("width", 200)
   .attr("height", 200)
svg.append("text")
   .attr("x", 50)
   .attr("y", 50)
   .attr("class", "text")
   .text("d3.js is awesome")